# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3-node-browsers
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: fremaApp
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_DATABASE: fremaApp
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root

    steps:
      - checkout

      - run: sudo apt update 
      # Install PHP Extension
      - run: sudo docker-php-ext-install pdo_mysql
      # composer
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # npm
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: |
            if [ ! -d node_modules ]; then 
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run dev

      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit